#run is used to execute commands directly on the runner, while uses is used to run external tools, actions, or Docker containers as part of the workflow. Each directive serves its purpose in different scenarios and provides flexibility in defining workflow steps.

name: Docker
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:20.3-alpine3.17
      # credentials:
      #   username:
      #   password:
      env:
        API_URL: some-url.com
      ports:
        - 80
      # volumes:
      #   - vol_name:/path/in/container
      #   - /path/to/container
      #   - /path/in/host:/path/in/container
      # options: --cpus 1
    steps:
      - name: Log Node & OS Versions   #runs on above container
        run: |
          node -v
          cat /etc/os-release
      - name: Log Env
        run: echo $API_URL
      - name: Container in a Step
        uses: docker://node:18.16-alpine3.17  #bit different way to add in steps than in job...for other reg different way
        with:
          entrypoint: /usr/local/bin/node   #cmd to find this path : type node   #override default entrypoint..not required to pass#node cmd
          args: -p 2+3   #cmd instruction
      - name: Log node version
        uses: docker://node:18.16-alpine3.17
        with:
          args: -v
