name: Run-on-docker-container
on: [workflow_dispatch]

jobs:
    Docker-Container-job:
        runs-on: ubuntu-latest
        container:
            image: node:21.6-alpine3.18
            # credentials:
             #   username:
             #   password:
            env:
                url: abc.com
            ports:
                - 80
              # volumes:
      #   - vol_name:/path/in/container
      #   - /path/to/container
      #   - /path/in/host:/path/in/container
      # options: --cpus 1
        steps:
            - name: Chcek version and os of image
              run: |
                    node -v
                    cat /etc/os-release
                    echo "$url"

