name: Chceking if key

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  Running-for-if-key:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Expressions
      run: |
        echo ${{ 1 }}
        echo ${{ 'This is a string' }}
        echo ${{ null }}
        echo ${{ true }}
        echo ${{ 1 > 2 }}
        echo ${{ 'string' == 'String' }}
        echo ${{ true && false }}
        echo ${{ true || (false && true) }}
    - name: Dump Contexts
      run: |
        echo '${{ toJson(github) }}'
        echo '${{ toJson(job) }}'
        echo '${{ toJson(secrets) }}'
        echo '${{ toJson(steps) }}'
        echo '${{ toJson(runner) }}'