name: Status Check Functions
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Step 2
        id: step-2
        run: exit 1  # to fail job
      - name: Runs on Failure 
      #if job fails...failure() if function which return true if job fails
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo 'Step 2 has failed'
      - name: Runs on Success
        if: success()    
         # This is not needed (DEFAULT BEAHAVIOUR), can skip aove if for success.
        run: echo 'Runs on Success'
      - name: Always Runs
        # if: success() || failure()
        if: always()
        run: echo 'Always Runs'
      - name: Runs When Cancelled
        if: cancelled()
        #if job cancelled , ot runs
        run: echo 'Runs on Cancelled'
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    #if job fails then only this run..it is dependent job on job-1
    steps:
      - run: echo 'Job 2'