name: Env variables and secrets
on: [push]

jobs:
    Env-var-with-secret:
        runs-on: ${{vars.RUNNER}}
        env:
            BOOLEAN_SECRET: ${{secrets.BOOLEAN_SECRET}}
            REPO_LEVEL_VAR: ${{vars.REPO_LEVEL_VAR}}
        steps:
         - name: Run only if BOOLEAN_SECRET is true
           if: env.BOOLEAN_SECRET == 'true'
           run: echo "I ran"
         - name: Log Vars
           run: |
            echo '${{ vars.RUNNER }}'
            echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
            echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR

